version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/start.sh
      runas: ubuntu
